import {
  UtensilsCrossed,
  Car,
  Ticket,
  Home,
  Zap,
  ShoppingBag,
  HeartPulse,
  MoreHorizontal,
  Briefcase,
  Gift,
} from 'lucide-react';
import type { Transaction, CategoryInfo, Budget } from '@/lib/types';

export const categories: CategoryInfo[] = [
  // Expenses
  { name: 'Food', icon: UtensilsCrossed, color: 'hsl(var(--chart-1))' },
  { name: 'Transportation', icon: Car, color: 'hsl(var(--chart-2))' },
  { name: 'Entertainment', icon: Ticket, color: 'hsl(var(--chart-3))' },
  { name: 'Housing', icon: Home, color: 'hsl(var(--chart-4))' },
  { name: 'Utilities', icon: Zap, color: 'hsl(var(--chart-5))' },
  { name: 'Shopping', icon: ShoppingBag, color: 'hsl(var(--chart-1))' },
  { name: 'Health', icon: HeartPulse, color: 'hsl(var(--chart-2))' },
  { name: 'Other', icon: MoreHorizontal, color: 'hsl(var(--chart-3))' },
  // Income
  { name: 'Salary', icon: Briefcase, color: 'hsl(var(--chart-1))' },
  { name: 'Freelance', icon: Briefcase, color: 'hsl(var(--chart-2))' },
  { name: 'Gift', icon: Gift, color: 'hsl(var(--chart-3))' },
];

export const transactions: Transaction[] = [
  {
    id: '1',
    date: new Date(new Date().setDate(new Date().getDate() - 2)),
    amount: 2500,
    type: 'income',
    category: 'Salary',
    description: 'Monthly Salary',
  },
  {
    id: '2',
    date: new Date(new Date().setDate(new Date().getDate() - 2)),
    amount: 55.4,
    type: 'expense',
    category: 'Food',
    description: 'Groceries',
  },
  {
    id: '3',
    date: new Date(new Date().setDate(new Date().getDate() - 3)),
    amount: 30,
    type: 'expense',
    category: 'Transportation',
    description: 'Gas',
  },
  {
    id: '4',
    date: new Date(new Date().setDate(new Date().getDate() - 4)),
    amount: 45,
    type: 'expense',
    category: 'Entertainment',
    description: 'Movie tickets',
  },
  {
    id: '5',
    date: new Date(new Date().setDate(new Date().getDate() - 5)),
    amount: 800,
    type: 'expense',
    category: 'Housing',
    description: 'Rent',
  },
  {
    id: '6',
    date: new Date(new Date().setDate(new Date().getDate() - 6)),
    amount: 75.2,
    type: 'expense',
    category: 'Utilities',
    description: 'Electricity Bill',
  },
  {
    id: '7',
    date: new Date(new Date().setDate(new Date().getDate() - 7)),
    amount: 120,
    type: 'expense',
    category: 'Shopping',
    description: 'New clothes',
  },
  {
    id: '8',
    date: new Date(new Date().setDate(new Date().getDate() - 8)),
    amount: 50,
    type: 'expense',
    category: 'Health',
    description: 'Pharmacy',
  },
  {
    id: '9',
    date: new Date(new Date().setDate(new Date().getDate() - 9)),
    amount: 25.0,
    type: 'expense',
    category: 'Food',
    description: 'Lunch out',
  },
  {
    id: '10',
    date: new Date(new Date().setDate(new Date().getDate() - 12)),
    amount: 1500,
    type: 'income',
    category: 'Freelance',
    description: 'Project X',
  },
  {
    id: '11',
    date: new Date(new Date().setDate(new Date().getDate() - 17)),
    amount: 15,
    type: 'expense',
    category: 'Transportation',
    description: 'Bus fare',
  },
  {
    id: '12',
    date: new Date(new Date().setDate(new Date().getDate() - 22)),
    amount: 60,
    type: 'expense',
    category: 'Food',
    description: 'Dinner with friends',
  },
];

export const budgets: Budget[] = [
  { category: 'Food', goal: 400 },
  { category: 'Transportation', goal: 100 },
  { category: 'Entertainment', goal: 150 },
  { category: 'Housing', goal: 800 },
  { category: 'Utilities', goal: 100 },
  { category: 'Shopping', goal: 200 },
  { category: 'Health', goal: 100 },
  { category: 'Other', goal: 50 },
];
